### ISSUE TITLE
How to Install？

### ISSUE THREAD

**Issue by amoyx** [elastic/uptime-contrib#8]
elasticsearch 7.3 version,  How to use it? Specific instructions

**Comment by justinkambic** [comment]
Hi - you can follow the instructions for importing saved objects in [the Kibana docs](https://www.elastic.co/guide/en/kibana/current/managing-saved-objects.html#_import_objects). 

Simply download the dashboard's JSON and import to Kibana.

**Comment by zhongcai1** [comment]
I downloaded http_dashboard.json. when trying to import to Kibana 7.4.0,  under Management /
Saved objects.  I got the following error: 

Support for JSON files is going away
Use our updated export to generate NDJSON files, and you'll be all set.

Sorry, there was an error
The file could not be processed.

**Comment by zhongcai1** [comment]
Never mind. 
My mistake: the http_dashboard.json I downloaded was corrupted (I downloaded it by right-click from github.com),  I should have downloaded the zip file instead.

**Comment by spyderz42** [comment]
I am getting this same NDJSON warning.. I have downloaded the raw file, cloned, and downloaded the zip. Trying to upload into kibana 7.4.0 complains about ndjson, and once I ignore that and try to import anyways it complains that 'Saved "field" parameter is now invalid. Please select a new field.' 3 times.
